---
- name: Apache Installation with Condition
  hosts: all
  become: yes
  tasks:
    - name: Update system packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Apache2 if not already installed
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"
      notify: Display message if Apache2 is installed

    - name: Start and enable Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"
      notify: Apache2 is started
    
  handlers:
    - name: Display message if Apache2 is installed
      debug:
        msg: "Apache2 is installed and running on this system."
    - name: Apache2 is started
      debug:
        msg: "Apache2 service has been started and enabled."