---
- name: apache2
  hosts: cible_docker
  tasks:
    - name: Vérifier si apache2 est installé
      apt: 
        name: apache2
        state: present
        update_cache: yes
    - name: Démarrer le service apache2
      service:
        name: apache2
        state: started
        enabled: yes
    - name: desinstalle apache2
      apt:
        name: apache2
        state: absent