
---
# tasks file for deploy-quiz-ansible

- name: Mettre à jour les paquets système
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Installer Git
  dnf:
    name: git
    state: present

- name: Télécharger le script d'installation Node.js
  get_url:
    url: "https://rpm.nodesource.com/setup_{{ node_version }}"
    dest: /tmp/nodejs_setup.sh
    mode: '0755'

- name: Exécuter le script téléchargé
  shell: /tmp/nodejs_setup.sh
  args:
    creates: /etc/yum.repos.d/nodesource-el8.repo

- name: Installer nodejs
  dnf:
    name: nodejs
    state: present

- name: Créer le répertoire /opt/
  file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0755'

- name:  Cloner le dépôt Git dans /opt/quiz-ansible
  git:
    repo: https://github.com/franklin-tutorials/quiz-ansible.git
    dest: "{{ app_dir }}"
    force: yes

- name: Installer les dépendances npm
  npm:
    path: "{{ app_dir }}"
    state: present

- name: Compiler l'application
  command: npm run build
  args:
    chdir: "{{ app_dir }}"

- name: Installer serve globalement
  npm:
    name: serve
    global: yes
    state: present

- name: Lancer l'application en arrière-plan
  shell: nohup serve -s dist > /dev/null 2>&1 &
  args:
    chdir: "{{ app_dir }}"